export const environment = {
  production: false,
  environment: 'qa',

  TIMEZONE: 'America/Sao_Paulo',

  API_SIMPLES_TYPEORM_TYPE: process.env.API_SIMPLES_TYPEORM_TYPE,
  API_SIMPLES_TYPEORM_PORT: process.env.API_SIMPLES_TYPEORM_PORT,
  API_SIMPLES_TYPEORM_SYNCHRONIZE: process.env.API_SIMPLES_TYPEORM_SYNCHRONIZE,

  API_SIMPLES_TYPEORM_HOSTNAME: process.env.API_SIMPLES_TYPEORM_HOSTNAME,
  API_SIMPLES_TYPEORM_USERNAME: process.env.API_SIMPLES_TYPEORM_USERNAME,
  API_SIMPLES_TYPEORM_PASSWORD: process.env.API_SIMPLES_TYPEORM_PASSWORD,
  API_SIMPLES_TYPEORM_DATABASE: process.env.API_SIMPLES_TYPEORM_DATABASE,


  API_PORT: 3333,
  API_HOST: 'localhost',
  JWT_SECRET: 'secredinhos 3D',
}
